<template>
  <section>
    <Dialog v-model:visible="dialogVisible" modal dismissable-mask :header="`เอกสาร ${selectedDocument}`" class="w-full max-w-6xl"><DataTable :value="documentRows" striped-rows><Column field="productCode" header="รหัสสินค้า" /><Column field="productName" header="ชื่อสินค้า" /><Column field="sourceQuantity" header="จำนวน" /><Column field="sourceUnitText" header="หน่วย" /><Column header="ยอดวิเคราะห์"><template #body="p">{{ money(p.data.analysisNetAmount) }}</template></Column></DataTable></Dialog>
    <div class="flex items-end justify-between"><div><p class="text-sm font-medium text-primary-600">Transaction Data</p><h2 class="mt-1 text-3xl font-semibold">Sales History</h2><p class="mt-2 text-sm text-surface-500">ข้อมูลที่ Import จาก Express สำหรับนำไปวิเคราะห์ Forecast</p></div><Button :label="importVisible ? 'ปิดส่วนนำเข้าข้อมูล' : 'นำเข้าข้อมูล'" :icon="importVisible ? 'pi pi-chevron-up' : 'pi pi-upload'" :severity="importVisible ? 'secondary' : 'primary'" @click="importVisible = !importVisible" /></div>
    <div v-if="importVisible" class="mt-6 rounded-xl border border-primary-200 bg-primary-50/30 p-6"><SalesHistoryImportView embedded @imported="handleImported" /></div>
    <div class="mt-6 grid gap-4 sm:grid-cols-3"><div class="rounded-xl border border-surface-200 bg-white p-5"><p class="text-sm text-surface-500">จำนวนข้อมูล</p><p class="mt-2 text-3xl font-semibold">{{ rows.length.toLocaleString('th-TH') }}</p><p class="mt-1 text-xs text-surface-400">แถว</p></div><div class="rounded-xl border border-surface-200 bg-white p-5"><p class="text-sm text-surface-500">ข้อมูลตั้งแต่วันที่</p><p class="mt-2 text-xl font-semibold">{{ firstDate ? date(firstDate) : '—' }}</p></div><div class="rounded-xl border border-surface-200 bg-white p-5"><p class="text-sm text-surface-500">ข้อมูลถึงวันที่</p><p class="mt-2 text-xl font-semibold">{{ lastDate ? date(lastDate) : '—' }}</p></div></div>
    <div class="mt-6 rounded-xl border border-surface-200 bg-white p-5"><DataTable :value="rows" :loading="loading" paginator :rows="25" :rows-per-page-options="[25,50,100]" striped-rows><template #empty>ยังไม่มีข้อมูล Sales History</template><Column field="transactionDate" header="วันที่" sortable><template #body="p">{{ date(p.data.transactionDate) }}</template></Column><Column header="เอกสาร"><template #body="p"><Button :label="p.data.documentNumber" link class="p-0" @click="openDocument(p.data.documentNumber)" /></template></Column><Column field="productCode" header="รหัสสินค้า" /><Column field="productName" header="ชื่อสินค้า" /><Column field="customerCode" header="ลูกค้า" /><Column header="ขาย/คืน"><template #body="p"><Tag :value="p.data.isReturn?'คืน':'ขาย'" :severity="p.data.isReturn?'danger':'success'" /></template></Column><Column field="sourceQuantity" header="จำนวน" /><Column field="sourceUnitText" header="หน่วย" /><Column header="ยอดวิเคราะห์"><template #body="p">{{ money(p.data.analysisNetAmount) }}</template></Column></DataTable></div><Message v-if="error" severity="error" class="mt-4">{{ error }}</Message>
  </section>
</template>
<script>
import Button from 'primevue/button'; import Column from 'primevue/column'; import DataTable from 'primevue/datatable'; import Dialog from 'primevue/dialog'; import Message from 'primevue/message'; import Tag from 'primevue/tag'
import SalesHistoryImportView from './SalesHistoryImportView.vue'; import { fetchSalesHistory } from '../../services/sales-history-data.js'
export default { name:'SalesHistoryListView', components:{Button,Column,DataTable,Dialog,Message,SalesHistoryImportView,Tag}, data(){return{rows:[],loading:true,error:'',dialogVisible:false,selectedDocument:'',importVisible:this.$route.query.import==='1'}}, computed:{documentRows(){return this.rows.filter(r=>r.documentNumber===this.selectedDocument)},firstDate(){return this.rows.reduce((v,r)=>!v||r.transactionDate<v?r.transactionDate:v,null)},lastDate(){return this.rows.reduce((v,r)=>!v||r.transactionDate>v?r.transactionDate:v,null)}}, async mounted(){await this.loadRows()}, methods:{async loadRows(){this.loading=true;this.error='';try{this.rows=await fetchSalesHistory()}catch(e){console.error(e);this.error='ไม่สามารถโหลด Sales History ได้'}finally{this.loading=false}},async handleImported(){await this.loadRows()},openDocument(v){this.selectedDocument=v;this.dialogVisible=true},date(v){return new Intl.DateTimeFormat('th-TH',{dateStyle:'medium'}).format(new Date(`${v}T00:00:00`))},money(v){return new Intl.NumberFormat('th-TH',{minimumFractionDigits:2}).format(v||0)}}}
</script><style scoped></style>
