<template>
  <section>
    <ConfirmDialog />
    <Dialog v-model:visible="dialog" modal dismissable-mask :header="`เอกสาร ${selectedDocument}`" class="w-full max-w-6xl">
      <DataTable :value="documentRows" striped-rows><Column field="productCode" header="รหัสสินค้า" style="width:14rem" /><Column field="productName" header="ชื่อสินค้า" /><Column field="sourceQuantity" header="จำนวน" /><Column field="sourceUnitText" header="หน่วย" /><Column header="ยอดสุทธิ"><template #body="p">{{ money(p.data.signedNetAmount) }}</template></Column></DataTable>
    </Dialog>
    <div v-if="!embedded"><p class="text-sm font-medium text-primary-600">Purchases · Purchase History</p><h2 class="mt-1 text-3xl font-semibold">Import from Express</h2><p class="mt-2 text-sm text-surface-500">รองรับการอัปเดตช่วงวันที่ซ้อนทับ และตรวจสอบก่อนบันทึก</p></div>
    <Message severity="warn" class="mt-6 max-w-5xl">ไฟล์ต้องมีรายการซื้อครบทั้งหมดภายในช่วงวันที่ในหัวรายงาน รายการที่หายไปในช่วงเดียวกันจะถูกปิดใช้งาน</Message>
    <section class="mt-6 max-w-5xl rounded-xl border border-surface-200 bg-white p-8">
      <div class="rounded-xl border-2 border-dashed border-surface-300 bg-surface-50 p-10 text-center"><i class="pi pi-file-arrow-up text-4xl text-primary-500" /><h3 class="mt-4 text-lg font-semibold">เลือกไฟล์ CSV Purchase History จาก Express</h3><FileUpload mode="basic" accept=".csv,text/csv" choose-label="เลือกไฟล์ CSV" custom-upload class="mt-6" :disabled="busy" @select="selectFile" /></div>
      <div v-if="file" class="mt-6 flex items-center justify-between rounded-lg border border-surface-200 p-4"><span>{{ file.name }} · {{ (file.size/1024).toFixed(1) }} KB</span><Button label="ตรวจสอบไฟล์" icon="pi pi-search" :loading="loading" :disabled="busy" @click="previewFile" /></div>
      <Message v-if="error" severity="error" class="mt-4">{{ error }}</Message>
    </section>
    <section v-if="preview" class="mt-6 max-w-[90rem] space-y-6">
      <Message :severity="preview.isValid?'success':'error'">{{ preview.isValid ? `ไฟล์ผ่านการตรวจสอบ ${date(preview.periodStart)} ถึง ${date(preview.periodEnd)}` : 'พบข้อผิดพลาด กรุณาตรวจสอบ Master Data' }}</Message>
      <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-7"><div v-for="card in cards" :key="card.label" class="rounded-xl border border-surface-200 bg-white p-4"><p class="text-xs text-surface-500">{{ card.label }}</p><p class="mt-1 text-2xl font-semibold">{{ card.value }}</p></div></div>
      <div v-if="preview.errors.length" class="rounded-xl border border-red-200 bg-white p-5 text-red-700"><p v-for="(item,i) in preview.errors" :key="i">บรรทัด {{ item.rowNumber||'-' }}: {{ item.message }}</p></div>
      <div class="rounded-xl border border-surface-200 bg-white p-5"><DataTable :value="preview.rows" paginator :rows="25" :rows-per-page-options="[25,50,100]" striped-rows><Column field="transactionDate" header="วันที่"><template #body="p">{{ date(p.data.transactionDate) }}</template></Column><Column header="เอกสาร"><template #body="p"><Button :label="p.data.documentNumber" link class="p-0" @click="openDocument(p.data.documentNumber)" /></template></Column><Column field="productCode" header="รหัสสินค้า" /><Column field="productName" header="ชื่อสินค้า" /><Column field="supplierCode" header="Supplier" /><Column header="ซื้อ/คืน"><template #body="p"><Tag :value="p.data.isReturn?'คืน':'ซื้อ'" :severity="p.data.isReturn?'danger':'success'" /></template></Column><Column field="sourceQuantity" header="จำนวน" /><Column field="sourceUnitText" header="หน่วย" /><Column header="ยอดสุทธิ"><template #body="p">{{ money(p.data.signedNetAmount) }}</template></Column><Column header="ผล"><template #body="p"><Tag :value="label(p.data.changeType)" :severity="severity(p.data.changeType)" /></template></Column></DataTable></div>
      <div v-if="preview.isValid&&!result" class="flex justify-end rounded-xl border border-surface-200 bg-white p-5"><Button label="ยืนยัน Import Purchase History" icon="pi pi-check" :loading="importing" :disabled="busy" @click="confirmDialog" /></div>
      <Message v-if="result" severity="success">{{ result.alreadyImported?'ไฟล์นี้เคย Import แล้ว':'Import Purchase History สำเร็จ' }} {{ result.summary.totalRows }} รายการ</Message>
    </section>
  </section>
</template>
<script>
import Button from 'primevue/button'; import Column from 'primevue/column'; import ConfirmDialog from 'primevue/confirmdialog'; import DataTable from 'primevue/datatable'; import Dialog from 'primevue/dialog'; import FileUpload from 'primevue/fileupload'; import Message from 'primevue/message'; import Tag from 'primevue/tag'
import { confirmPurchaseHistoryFile, previewPurchaseHistoryFile } from '../../services/purchase-history.js'
export default { name:'PurchaseHistoryImportView',components:{Button,Column,ConfirmDialog,DataTable,Dialog,FileUpload,Message,Tag},props:{embedded:{type:Boolean,default:false}},emits:['imported'],data(){return{file:null,preview:null,result:null,loading:false,importing:false,error:'',dialog:false,selectedDocument:''}},computed:{busy(){return this.loading||this.importing},cards(){const s=this.preview?.summary;return s?[{label:'ทั้งหมด',value:s.totalRows},{label:'รายการคืน',value:s.returnCount},{label:'สร้างใหม่',value:s.createCount},{label:'อัปเดต',value:s.updateCount},{label:'ไม่เปลี่ยน',value:s.unchangedCount},{label:'จะปิด',value:s.deactivateCount},{label:'ข้อผิดพลาด',value:s.errorCount}]:[]},documentRows(){return this.preview?.rows.filter(r=>r.documentNumber===this.selectedDocument)||[]}},methods:{selectFile(e){this.file=e.files[0]||null;this.preview=null;this.result=null;this.error=''},async previewFile(){if(this.busy)return;this.loading=true;this.error='';try{this.preview=await previewPurchaseHistoryFile(this.file)}catch(e){console.error(e);this.error=e.message||'ไม่สามารถตรวจสอบไฟล์ได้'}finally{this.loading=false}},openDocument(v){this.selectedDocument=v;this.dialog=true},confirmDialog(){this.$confirm.require({header:'ยืนยัน Import Purchase History',message:`ระบบจะบันทึก ${this.preview.summary.totalRows} รายการ ต้องการดำเนินการต่อหรือไม่`,rejectLabel:'ยกเลิก',acceptLabel:'ยืนยัน Import',accept:()=>{this.$confirm.close();void this.importFile()}})},async importFile(){if(this.busy)return;this.importing=true;this.error='';try{this.result=await confirmPurchaseHistoryFile(this.file,this.preview.previewId);this.$emit('imported',this.result)}catch(e){console.error(e);this.error=e.message||'ไม่สามารถ Import ได้'}finally{this.importing=false}},date(v){return new Intl.DateTimeFormat('th-TH',{dateStyle:'medium'}).format(new Date(`${v}T00:00:00`))},money(v){return new Intl.NumberFormat('th-TH',{minimumFractionDigits:2}).format(v||0)},label(v){return{create:'สร้างใหม่',update:'อัปเดต',unchanged:'ไม่เปลี่ยน'}[v]||v},severity(v){return{create:'success',update:'warn',unchanged:'secondary'}[v]||'secondary'}}}
</script>
<style scoped></style>
